[build-system]
requires = [
    "setuptools>=61.0",  
    "torch>=2.5.1"
    ]
build-backend = "setuptools.build_meta"

[tool.pixi.workspace]
name = "medsam2-recist"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
MedSAM2 = { path = ".", editable = true }
opencv-python = ">=4.10.0,<5"

[tool.pixi.tasks]

[tool.pixi.dependencies]
matplotlib = ">=3.10.7,<4"
jupyter = ">=1.1.1,<2"
black = ">=25.1.0,<26"
usort = ">=1.0.8.post1,<2"
ufmt = ">=2.9.0,<3"
fvcore = ">=0.1.5.post20221221,<0.2"
pandas = ">=2.3.3,<3"
scikit-image = ">=0.25.2,<0.26"
tensorboard = ">=2.20.0,<3"
pycocotools = ">=2.0.10,<3"
tensordict = ">=0.10.0,<0.11"
submitit = ">=1.5.2,<2"
